// 📁 PATH: src/mpesa/account-balance/types.ts

/**
 * Account Balance Query types
 *
 * API: POST /mpesa/accountbalance/v1/query
 *
 * Queries the current balance of an M-PESA shortcode.
 * This is ASYNCHRONOUS — the sync response is only acknowledgement.
 * Balance data is POSTed to your ResultURL callback.
 *
 * Required org portal role: "Balance Query ORG API" (Account Balance ORG API initiator)
 *
 * Ref: Account Balance — Daraja Developer Portal
 */

// ── Error codes (documented by Daraja) ───────────────────────────────────────

/**
 * Documented Account Balance API error/result codes.
 * These appear in the async callback ResultCode field.
 *
 * Ref: Account Balance — Error Codes section
 */
export const ACCOUNT_BALANCE_ERROR_CODES = {
  /** 15 — Duplicate Detected: OriginatorConversationID has been seen before */
  DUPLICATE_DETECTED: 15,
  /** 17 — Internal Failure: catch-all for unidentified failures */
  INTERNAL_FAILURE: 17,
  /** 18 — Initiator Credential Check Failure: wrong password or encryption issue */
  INITIATOR_CREDENTIAL_CHECK_FAILURE: 18,
  /** 19 — Message Sequencing Failure */
  MESSAGE_SEQUENCING_FAILURE: 19,
  /** 20 — Unresolved Initiator: initiator username not found */
  UNRESOLVED_INITIATOR: 20,
  /** 21 — Initiator to Primary Party Permission Failure */
  INITIATOR_TO_PRIMARY_PARTY_PERMISSION_FAILURE: 21,
  /** 22 — Initiator to Receiver Party Permission Failure: initiator not active */
  INITIATOR_TO_RECEIVER_PARTY_PERMISSION_FAILURE: 22,
  /** 24 — Missing Mandatory Fields */
  MISSING_MANDATORY_FIELDS: 24,
  /** 100000001 — System Overload */
  SYSTEM_OVERLOAD: 100000001,
  /** 100000002 — Throttling Error */
  THROTTLING_ERROR: 100000002,
  /** 100000004 — Internal Server Error */
  INTERNAL_SERVER_ERROR: 100000004,
  /** 100000005 — Invalid Input Value: %1 indicates the parameter's name */
  INVALID_INPUT_VALUE: 100000005,
  /** 100000007 — Service's status is abnormal */
  SERVICE_ABNORMAL: 100000007,
  /** 100000009 — API's status is abnormal */
  API_STATUS_ABNORMAL: 100000009,
  /** 100000010 — Insufficient permissions */
  INSUFFICIENT_PERMISSIONS: 100000010,
  /** 100000011 — Exceed the limitation of request rate */
  REQUEST_RATE_EXCEEDED: 100000011,
} as const

export type AccountBalanceErrorCode =
  (typeof ACCOUNT_BALANCE_ERROR_CODES)[keyof typeof ACCOUNT_BALANCE_ERROR_CODES]

// ── Request ───────────────────────────────────────────────────────────────────

export interface AccountBalanceRequest {
  /**
   * Your business shortcode from which balance is queried.
   * Daraja field: PartyA (Numeric)
   * Example: "600000"
   */
  partyA: string

  /**
   * Type of the PartyA identifier.
   *   "1" = MSISDN
   *   "2" = Till Number
   *   "4" = Organisation ShortCode (most common — Paybill/B2C/Buy Goods)
   * Daraja field: IdentifierType (Numeric)
   * Sample: 4
   */
  identifierType: '1' | '2' | '4'

  /**
   * URL where Safaricom POSTs the balance result (async callback).
   * Must be publicly accessible. HTTPS required in production.
   * Daraja field: ResultURL (URL)
   * Sample: https://ip:port/path or domain:port/path
   */
  resultUrl: string

  /**
   * URL Safaricom calls when the request times out.
   * Daraja field: QueueTimeOutURL (URL)
   * Sample: https://ip:port/path or domain:port/path
   */
  queueTimeOutUrl: string

  /**
   * Comments sent along with the transaction (up to 100 characters).
   * Daraja field: Remarks (String)
   * Sample: ok
   */
  remarks?: string
}

// ── Synchronous acknowledgement ───────────────────────────────────────────────

/**
 * Synchronous response from Daraja confirming the request was received.
 * This is NOT the balance data — balance arrives via async callback to ResultURL.
 *
 * ResponseCode "0" = request accepted for processing.
 */
export interface AccountBalanceResponse {
  /** Unique identifier of the request. Auto-generated by M-PESA. */
  OriginatorConversationID: string
  /** Unique identifier generated by M-PESA for this request */
  ConversationID: string
  /** "0" = request accepted by Mobile Money */
  ResponseCode: string
  /** Description of the ResponseCode */
  ResponseDescription: string
}

// ── Async result (POSTed to ResultURL) ───────────────────────────────────────

/**
 * AccountBalance result parameter key names as documented by Daraja.
 */
export type AccountBalanceResultParameterKey = 'AccountBalance' | 'BOCompletedTime'

/**
 * A single result parameter entry from the Daraja callback.
 */
export interface AccountBalanceResultParameter {
  Key: AccountBalanceResultParameterKey | string
  Value: string | number
}

/**
 * The ReferenceItem from the async callback.
 * Key is typically "QueueTimeoutURL" as documented.
 */
export interface AccountBalanceReferenceItem {
  Key: string
  Value: string
}

/**
 * Full async callback payload POSTed to your ResultURL after processing.
 *
 * ResultCode 0 = success; non-zero = failure.
 *
 * ResultParameters.ResultParameter contains:
 *   - AccountBalance: pipe-delimited balance string for all accounts
 *   - BOCompletedTime: completion timestamp (format: YYYYMMDDHHmmss)
 *
 * Ref: Callback Result Payload — Daraja Account Balance docs
 */
export interface AccountBalanceResult {
  Result: {
    /**
     * ResultType:
     *   "0" = completed
     *   "1" = waiting for further messages
     */
    ResultType: string | number
    /**
     * Result code indicating success or failure.
     * 0 = success; see ACCOUNT_BALANCE_ERROR_CODES for failure codes.
     * Note: Daraja may return this as string "0" or number 0 on success.
     */
    ResultCode: number | string
    /** Human-readable description of the result */
    ResultDesc: string
    /** Unique identifier from the original request */
    OriginatorConversationID: string
    /** Unique identifier generated by M-PESA */
    ConversationID: string
    /** M-PESA transaction identifier */
    TransactionID: string
    /** Balance data — only present on success (ResultCode 0) */
    ResultParameters?: {
      /**
       * Can be an array (multiple params) or a single object (Daraja inconsistency).
       * Use getAccountBalanceParam() to handle both forms safely.
       */
      ResultParameter: AccountBalanceResultParameter[] | AccountBalanceResultParameter
    }
    /** Reference data Daraja records in transaction logs */
    ReferenceData?: {
      ReferenceItem: AccountBalanceReferenceItem | AccountBalanceReferenceItem[]
    }
  }
}

// ── Parsed account types ──────────────────────────────────────────────────────

/**
 * Balance data for a single M-PESA account type.
 *
 * Daraja returns balance for all account types as a single pipe-delimited string.
 * Each group is: AccountName|Currency|Amount
 * Multiple groups are concatenated with pipe separators.
 *
 * Documented account types:
 *   - Working Account (MMF): transition account for bank settlement
 *   - Utility Account: receives customer payments (C2B/Buy Goods)
 *   - Charges Paid Account: deducts charges per business tariff
 *   - Organization Settlement: after charges deducted, money passes to working
 *
 * Example raw string:
 *   "Working Account|KES|700000.00|KES|0.00|KES|0.00|Utility Account|KES|228037.00|..."
 */
export interface ParsedAccount {
  /** Account name e.g. "Working Account", "Utility Account", "Charges Paid Account" */
  name: string
  /** Currency code e.g. "KES" */
  currency: string
  /** Amount as string (preserves Daraja format, may be negative for Charges Paid) */
  amount: string
}

export interface AccountBalanceData {
  /** Raw pipe-delimited string from Daraja AccountBalance result parameter */
  rawBalance: string
  /** Parsed accounts — one entry per account type in the shortcode */
  accounts: ParsedAccount[]
}

// ── Parsers ───────────────────────────────────────────────────────────────────

/**
 * Parses the raw Daraja AccountBalance string into structured account objects.
 *
 * Daraja returns each account as 3 consecutive pipe-separated fields:
 *   AccountName | Currency | Amount
 * Multiple accounts are concatenated, with additional balance sub-fields interleaved.
 *
 * The parser extracts triplets where the first element is a non-numeric account name.
 *
 * Example input:
 *   "Working Account|KES|700000.00|KES|0.00|KES|0.00|Utility Account|KES|228037.00|"
 *
 * Example output:
 *   [
 *     { name: "Working Account", currency: "KES", amount: "700000.00" },
 *     { name: "Utility Account", currency: "KES", amount: "228037.00" },
 *   ]
 */
export function parseAccountBalance(raw: string): ParsedAccount[] {
  if (!raw.trim()) return []

  const parts = raw.split('|')
  const accounts: ParsedAccount[] = []

  for (let i = 0; i + 2 < parts.length; i++) {
    const candidate = parts[i]?.trim()
    const currency = parts[i + 1]?.trim()
    const amount = parts[i + 2]?.trim()

    // An account name starts a new group — it is non-numeric and non-empty
    // Numeric-only parts are sub-fields (uncleared/reserved) — skip them
    if (
      candidate &&
      currency &&
      amount !== undefined &&
      isNaN(Number(candidate)) &&
      candidate.length > 0
    ) {
      accounts.push({ name: candidate, currency, amount })
    }
  }

  return accounts
}

// ── Result parameter extractor ────────────────────────────────────────────────

/**
 * Extracts a result parameter value from an AccountBalanceResult by key.
 * Handles both array and single-object forms of ResultParameter (Daraja inconsistency).
 *
 * Documented keys: "AccountBalance", "BOCompletedTime"
 */
export function getAccountBalanceParam(
  result: AccountBalanceResult,
  key: string,
): string | number | undefined {
  const params = result.Result.ResultParameters?.ResultParameter
  if (!params) return undefined
  const arr = Array.isArray(params) ? params : [params]
  return arr.find((p) => p.Key === key)?.Value
}

// ── Field extractor helpers ───────────────────────────────────────────────────

/**
 * Returns the M-PESA TransactionID from the result.
 */
export function getAccountBalanceTransactionId(result: AccountBalanceResult): string {
  return result.Result.TransactionID
}

/**
 * Returns the ConversationID from the result.
 */
export function getAccountBalanceConversationId(result: AccountBalanceResult): string {
  return result.Result.ConversationID
}

/**
 * Returns the OriginatorConversationID from the result.
 * This correlates the callback to the original request.
 */
export function getAccountBalanceOriginatorConversationId(result: AccountBalanceResult): string {
  return result.Result.OriginatorConversationID
}

/**
 * Returns the BOCompletedTime from the result parameters, or null if not present.
 * Format: YYYYMMDDHHmmss (e.g. "20200109125710")
 */
export function getAccountBalanceCompletedTime(result: AccountBalanceResult): string | null {
  const value = getAccountBalanceParam(result, 'BOCompletedTime')
  if (value === undefined || value === null) return null
  return String(value)
}

/**
 * Returns the raw AccountBalance pipe-delimited string from the result, or null if absent.
 * Use parseAccountBalance() to parse this into structured account objects.
 */
export function getAccountBalanceRawBalance(result: AccountBalanceResult): string | null {
  const value = getAccountBalanceParam(result, 'AccountBalance')
  if (value === undefined || value === null) return null
  return String(value)
}

/**
 * Returns the ReferenceItem from the async callback, or null if not present.
 * Key is typically "QueueTimeoutURL" as documented by Daraja.
 */
export function getAccountBalanceReferenceItem(
  result: AccountBalanceResult,
): AccountBalanceReferenceItem | null {
  const refData = result.Result.ReferenceData
  if (!refData) return null
  const item = refData.ReferenceItem
  if (!item) return null
  return Array.isArray(item) ? (item[0] ?? null) : item
}

// ── Result type guard ─────────────────────────────────────────────────────────

/**
 * Returns true if the Account Balance result indicates success (ResultCode 0).
 * Handles both numeric 0 and string "0" (Daraja inconsistency).
 */
export function isAccountBalanceSuccess(result: AccountBalanceResult): boolean {
  const code = result.Result.ResultCode
  return code === 0 || code === '0'
}
